homepage/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('addFriend/', views.addFriend, name='addFriend'),
    path('seeFriend/', views.seeFriend, name='seeFriend'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

#Create your models here.
class ClassYear(models.Model):
    BATCH_CHOICES= [('Maung (2019)', 'Maung (2019)'),
    ('Quanta (2018)', 'Quanta (2018)'),
    ('Tarung (2017)', 'Tarung (2017)'),
    ('Omega (2016)', 'Omega (2016)'),
    ('Others', 'Others')]
    batch = models.CharField(max_length=255, choices=BATCH_CHOICES, default='NULL')

    def __str__(self):
        return self.batch

class Friend(models.Model):
    name = models.CharField(max_length=255, primary_key=True)
    ClassYear = models.ForeignKey(ClassYear, on_delete=models.CASCADE, default='NULL')
    hobby = models.CharField(max_length=255)
    favFoodDrink = models.CharField(max_length=255,)

    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from .models import Friend, ClassYear

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['name', 'ClassYear', 'hobby', 'favFoodDrink']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Friend, ClassYear
from . import forms

# Create your views here.
def index(request):
    return render(request, 'index.html')

def seeFriend(request):
    friend = Friend.objects.all()
    classyear = ClassYear.objects.all()
    response = {'friend' : friend, 'classyear': classyear}
    return render(request, 'seeFriend.html', response)

def addFriend(request):
    if request.method == 'POST':
        form = forms.FriendForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:seeFriend')
    else:
        form = forms.FriendForm()
    return render(request, 'addFriend.html', {'form': form})

homepage/templates/addFriend.html
{% block content %}
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <title>Friend List</title>

  </head>
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"> 
  <body style="font-family: 'Roboto', sans-serif; background-color: #c4c4c4;">
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top" id="mainNav">
        <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNa  v">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link js-scroll-trigger" href="{% url 'homepage:index' %}">home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                friends
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'homepage:seeFriend' %}">view</a>
              </div>
            </li>
          </ul>
        </div>
        </div>
      </nav>

<br><br><br><br>

<h class="font-weight-bold" style="font-size: 5vh; margin-left: 8.7%;">add friends</h>
<br><br>
<form method="post" action="{% url 'homepage:addFriend' %}">
    {% csrf_token %}
    <div style="margin-left: 10px; margin-right: 10px;">
    <div class="form-row">
        <div class="col-sm-1"></div>
        <div class="form-group col-sm-10">
            {% for fields in form %}
                {{ fields.label_tag }}
                <br>
                {{ fields }}
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <input id="submitBtn" type="submit" class="btn btn-secondary" style="margin-left: 8.7%;" value="Add">
    </div>
</form>
</div>
      

      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>
{% endblock %}

homepage/templates/copyright.html
<div style="color: #000000;background-color:white;text-align:center;">
    <h4 style="text-align:center;">(c)2020 olivermf</h4>
</div>
    

homepage/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <!-- my CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Story 4</title>

  </head>
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"> 
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top" id="mainNav">
      <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link js-scroll-trigger" href="#pg1">home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link js-scroll-trigger" href="#pg2">about<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              friends
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'homepage:addFriend' %}">add</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'homepage:seeFriend' %}">view</a>
            </div>
          </li>
        </ul>
      </div>
      </div>
    </nav>
    <section class="page1" id="pg1">
      <br><br><br>
      <div class="container-fluid">
        <div class="row">
          <div class="col">
              <div class="name">
                   <p class="pName">Oliver<br>Muhammad<br>Fadhlurrahman</p>
                  <p class="pNpm">1 8 0 6 2 5 1 1 5 4</p>
              </div>
          </div>
          <div class="col text-right">
              <div class="about">
                  <!-- <a class="text-dark" href="#pg2">about</a> -->
                  <!-- <a class="text-dark" href="#pg3">page3</a> -->
              </div>
          </div>
        </div>
      </div>
      <br>
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="col text-left">
              <p class="pQuote">you should do what you said you were going to do that one time before you got all tired and<br>then got super busy and pretty much forgot you really should</p>
          </div>
          <div class="col text-right">
              <img class="pp" src="{% static 'images/profilepic.png' %}">
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <div class="row">
          <div class="col">
              <p class="pUni1">University of<br>Indonesia</p>
              <p class="pUni2">Faculty of Computer Science</p>
          </div>
        </div>
      </div>
    </section>

    <section class="page2" id="pg2">
      <br><br><br>
      <div class="container-fluid">
        <div class="row align-items-center" style="padding-left: 8%; padding-right: 8%;">
          <div class="col text-left">
            <img class="imgPage2" src="{% static 'images/page2.png' %}">
          </div>
          <div class="col text-center">
            <p class="pBio">Hello there! I'm an undergraduate<br>student in Fasilkom UI, currently<br>on my 2nd year. I take the<br>interational class program, so if all<br>goes well I'm gonna continue my<br>studies in Australia next year!<br>Hope I can do well this semester!</p>
          </div>
        </div>
      </div>
      <br><br>
      <div class="d-flex align-items-center">
        <div class="rect4"></div>
        <p class="pBioTitle">B I O</p>
        <div class="rect5 flex-grow-1"></div>
      </div>
    </section>

    <section class="page3" id="pg3">
      <div class="d-flex align-items-center">
        <div class="rect7"></div>
        <p class="pHobby">H O<br>B B Y</p>
        <div class="rect8 flex-grow-1"></div>
      </div>
      <div class="container-fluid">
        <div class="row" style="padding-left: 5%; padding-right: 8%;">
          <div class="col-8">
            <div class="row">
              <div class="col">
                <img class="hby" src="{% static 'images/travel.png' %}">
              </div>
              <div class="col">
                <img class="hby" src="{% static 'images/movie.png' %}">
              </div>
              <div class="col">
                <img class="hby" src="{% static 'images/fgo.png' %}">
              </div>
              <div class="col">
                <img class="hby" src="{% static 'images/gamecube.png' %}">
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="container-fluid text-right">
        <div class="row" style="padding-left: 8%; padding-right: 5%;">
          <div class="col-6"></div>
          <div class="col-6">
            <div class="row">
              <div class="col">
                <img class="skl" src="{% static 'images/psql.png' %}">
              </div>
              <div class="col">
                <img class="skl" src="{% static 'images/java.png' %}">
              </div>
              <div class="col">
                <img class="skl" src="{% static 'images/py.png' %}">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="d-flex align-items-center">
        <div class="rect13 flex-grow-1"></div>
        <p class="pSkills">S K I<br>L L S</p>
        <div class="rect14"></div>
      </div>
    </section>
    {% include 'copyright.html' %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

homepage/templates/seeFriend.html
{% block content %}
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <title>Friend List</title>

  </head>
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"> 
  <body style="font-family: 'Roboto', sans-serif; background-color: #c4c4c4;">
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top" id="mainNav">
        <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNa  v">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link js-scroll-trigger" href="{% url 'homepage:index' %}">home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                friends
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'homepage:addFriend' %}">add</a>
              </div>
            </li>
          </ul>
        </div>
        </div>
      </nav>
      <hr>
      <br><br>
      <div class="container-fluid">
        <div class="row text-center">
          <div class="col">
            <h class="font-weight-bold" style="font-size: 5vh;">friend list</h>
          </div>
        </div>
      </div>
      <br>
      <table id="friendtable" class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Batch</th>
            <th scope="col">Hobby</th>
            <th scope="col">Fav Food/Drink</th>
          </tr>
        </thead>
        <tbody>
          {% for friend in friend %}
            <tr class="table-info">
              <td class="table-secondary">{{ friend.name }}</td>
              <td class="table-info">{{ friend.ClassYear }}</td>
              <td class="table-secondary">{{ friend.hobby }}</td>
              <td class="table-info">{{ friend.favFoodDrink }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>
{% endblock %}